# Generated by Django 3.2.3 on 2024-12-18 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recipe_ingredient', to='api.ingredient', verbose_name='Ингредиент из рецепта'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recipe_ingredient', to='api.recipe', verbose_name='Рецепт'),
        ),
    ]
