# Generated by Django 3.2.3 on 2024-12-15 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20241126_0431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourites',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.RemoveConstraint(
            model_name='favourites',
            name='unique_favourites',
        ),
    ]
